version: '3.1'

services:
  api-reservation-db:
    container_name: api-reservation-db
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
      
  redisinsight:
    image: redislabs/redisinsight:1.11.0
    ports:
      - '8001:8001'
