spring:
  application:
    name: discovery-server
  profiles:
    active: native

server:
  port: 8761
  error:
    include-stacktrace: never
  servlet:
    context-path: /discovery-server

  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: info,health,refresh,bus-refresh

  info:
    java:
      enabled: false #change if you want to obtain information about Java
    os:
      enabled: false #change if you want to obtain information about OS
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: false
info:
  app:
    name: "@project.artifactId@"
    version: "@project.version@"
  contact:
    email: "sacco.andres@gmail.com"
    slack: "adsacco"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false