version: '3.1'
services:
  api-catalog:
    image: adschosen/api-catalog:1.0.0
    container_name: api-catalog
    ports:
     - 6070:6070
    restart: always 
    links:
      - api-catalog-db
      
  api-catalog-db:
    container_name: api-catalog-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_catalog'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
      - 3310:3306

  api-clusters:
    image: adschosen/api-clusters:1.0.0
    container_name: api-clusters
    ports:
     - 4070:4070
    restart: always
    links:
      - api-clusters-db

  api-clusters-db:
    container_name: api-clusters-db
    image: redis:alpine
    restart: always
    ports:
      - 6079:6379

  api-itineraries-search:
    image: adschosen/api-itineraries-search:1.0.0
    container_name: api-itineraries-search
    ports:
     - 7070:7070
    restart: always

  api-pricing:
    image: adschosen/api-pricing:1.0.0
    container_name: api-pricing
    ports:
     - 5070:5070
    restart: always

  api-pricing-db:
    container_name: api-pricing-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_pricing'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
      - 3311:3306

  api-provider-alpha:
    image: adschosen/api-provider-alpha:1.0.0
    container_name: api-provider-alpha
    ports:
     - 8070:8070
    restart: always

  api-provider-beta:
    image: adschosen/api-provider-beta:1.0.0
    container_name: api-provider-beta
    ports:
     - 9070:9070
    restart: always
    
  api-reservation-db:
    container_name: api-reservation-db
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_reservation'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
      - 3312:3306
      
  config-server-messaging:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP protocol (used by Spring Cloud Bus)
      - "15672:15672"    # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
