{
 "title": "Loki Logs Overview",
 "refresh": "10s",
 "panels": [
  {
   "title": "Logs by Level (Graph)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "count_over_time({app=\"api-reservation\"} |= \"ERROR\" [5m])",
     "legendFormat": "ERROR"
    },
    {
     "expr": "count_over_time({app=\"api-reservation\"} |= \"WARN\" [5m])",
     "legendFormat": "WARN"
    },
    {
     "expr": "count_over_time({app=\"api-reservation\"} |= \"INFO\" [5m])",
     "legendFormat": "INFO"
    }
   ]
  },
  {
   "title": "Error Log Count (Last 1h)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 10, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "count_over_time({app=\"spring-boot-app\"} |= \"ERROR\" [1h])"
    }
   ]
  },
  {
   "title": "Warning Log Count (Last 1h)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 10, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "count_over_time({app=\"api-reservation\"} |= \"WARN\" [1h])"
    }
   ]
  },
  {
   "title": "Debug Log Count (Last 1h)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 10, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "count_over_time({app=\"api-reservation\"} |= \"DEBUG\" [1h])"
    }
   ]
  },
  {
   "title": "Info Log Count (Last 1h)",
   "type": "stat",
   "gridPos": { "x": 18, "y": 10, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "count_over_time({app=\"api-reservation\"} |= \"INFO\" [1h])"
    }
   ]
  },
  {
   "title": "Logs per Level",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{app=\"api-reservation\"}"
    }
   ]
  }
 ]
}