global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/api/flights/reservation/management/prometheus'
    static_configs:
      - targets: ['api-reservation:8090'] # Or 'springboot:8080' if containerized

