
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/andres-sacco/deguyer-spring-boot-microservices.git
          default-label: main
          clone-on-start: true
          search-paths: config
          # For private repositories use this attributes
          # username: your-username
          # password: your-personal-access-token
      
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8888
  error:
    include-stacktrace: never
  servlet:
    context-path: /config-server

  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: info,health,refresh,bus-refresh

  info:
    java:
      enabled: false #change if you want to obtain information about Java
    os:
      enabled: false #change if you want to obtain information about OS
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: false
info:
  app:
    name: "@project.artifactId@"
    version: "@project.version@"
  contact:
    email: "sacco.andres@gmail.com"
    slack: "adsacco"
