version: '3.1'

services:
  api-reservation-db:
    container_name: api-reservation-db
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: flights_reservation
    ports:
      - 27017:27017

